task_name: image_logicnlg_debug
path: ${TABLEEVAL_DATA_ROOT}/LogicNLG/debug_subset
test_split: test
validation_split: validation
train_split: train
num_fewshot: 0
save_columns: instance_id,image_name,filename,table_id,title
instruction: ""
doc_to_text: !function image_parser.parse
doc_to_target: ref
multi_modal_data: True
metric_list:
  - sacrebleu
  - moverS
