task_name: image_comtqa_pmc_debug
path: ${TABLEEVAL_DATA_ROOT}/ComTQA/PubTab1M/debug_subset
test_split: train
train_split: train
num_fewshot: 0
save_columns: instance_id,id,image_name
instruction: ""
doc_to_text: !function image_parser.parse
doc_to_target: answer
multi_modal_data: True
metric_list:
  - accuracy
  - f1
  - sacrebleu
  - moverS
